BusinessApp.MvcWebUI/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessApp.CarpetWash.DataAccess.Concrete.EntityFramework;
using BusinessApp.CarpetWash.Entities.Concrete;
using BusinessApp.CarpetWash.Business.Abstract;
using Microsoft.AspNetCore.Authorization;

namespace BusinessApp.CarpetWash.MvcWebUI.Controllers
{
    [Authorize]
    public class TagsController : Controller
    {
        private readonly ITagService _tagService;
        public TagsController(ITagService tagService)
        {
            _tagService = tagService;
        }

        // GET: Tags
        public async Task<IActionResult> Index()
        {
            return View(await _tagService.GetAllTagsAsync());
        }

        // GET: Tags/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _tagService.FindTagByIdAsync(id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // GET: Tags/Create
        public IActionResult Create()
        {
            //TODO: This can be added later on.
            //ViewData["ContentId"] = new SelectList(_context.Contents, "Id", "Id");
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,ContentId,Slug,ItemType,Name,CreatedAt,UpdatedAt")] Tag tag)
        {
            //TODO: This can be added later on.
            if (ModelState.IsValid)
            {
                //_context.Add(tag);
                //await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["ContentId"] = new SelectList(_context.Contents, "Id", "Id", tag.ContentId);
            return View(tag);
        }

        // GET: Tags/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            //TODO: This can be enhanced later on
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _tagService.FindTagByIdAsync(id);
            if (tag == null)
            {
                return NotFound();
            }
            //ViewData["ContentId"] = new SelectList(_context.Contents, "Id", "Id", tag.ContentId);
            return View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ContentId,Slug,ItemType,Name,CreatedAt")] Tag tag)
        {
            if (id != tag.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    tag.UpdatedAt = DateTime.Now;
                    await _tagService.UpdateAsync(tag);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await TagExists(tag.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tags/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _tagService.FindTagByIdAsync(id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _tagService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        private async Task<bool> TagExists(int id)
        {
            return await _tagService.Exist(id);
        }
    }
}

BusinessApp.MvcWebUI/Views/Tags/Create.cshtml
@model BusinessApp.CarpetWash.Entities.Concrete.Tag

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Basic form -->
<div class="col-md-12">
    <div class="panel panel-default">
        <header class="panel-heading">Create New Tag</header>
        <div class="panel-body">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ContentId" class="control-label"></label>
                    <select asp-for="ContentId" class="form-control" asp-items="ViewBag.ContentId"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Slug" class="control-label"></label>
                    <input asp-for="Slug" class="form-control" />
                    <span asp-validation-for="Slug" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ItemType" class="control-label"></label>
                    <input asp-for="ItemType" class="form-control" />
                    <span asp-validation-for="ItemType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">Create New Tag</button>
                    <a asp-action="Index" class="btn btn-danger">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>

BusinessApp.MvcWebUI/Views/Tags/Delete.cshtml
@model BusinessApp.CarpetWash.Entities.Concrete.Tag

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="col-md-12">
    <div class="panel panel-default">
        <header class="panel-heading">Are you sure you want to delete this?</header>
        <div class="panel-body">
            <div class="form-group">
                @Html.DisplayFor(model => model.Name)
            </div>
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <button type="submit" class="btn btn-danger">Delete</button>
                <a asp-action="Index" class="btn btn-default">Back to List</a>
            </form>
        </div>
    </div>
</div>

BusinessApp.MvcWebUI/Views/Tags/Details.cshtml
@model BusinessApp.CarpetWash.Entities.Concrete.Tag

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!-- Content start -->
    <div class="container-fluid">
        <!-- Statistics panels -->
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <header class="panel-heading">Panel title</header>
                    <div class="panel-body">
                        <dl class="row">
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Slug)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Slug)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.ItemType)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.ItemType)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Name)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.CreatedAt)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.CreatedAt)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.UpdatedAt)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.UpdatedAt)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Content)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Content.Id)
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Statistics panels -->
        <div>
            <a asp-action="Index" class="btn btn-link">Back to List</a>
        </div>
    </div>

BusinessApp.MvcWebUI/Views/Tags/Edit.cshtml
@model BusinessApp.CarpetWash.Entities.Concrete.Tag

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Basic form -->
<div class="col-md-12">
    <div class="panel panel-default">
        <header class="panel-heading">Edit New Tag</header>
        <div class="panel-body">
            <form role="form" asp-action="Edit">
                <input asp-for="Id" class="form-control" type="hidden" />
                <input asp-for="CreatedAt" class="form-control" type="hidden" />
                <input asp-for="ContentId" class="form-control" type="hidden" />
                
                <div class="form-group">
                    <label asp-for="Slug" class="control-label"></label>
                    <input asp-for="Slug" class="form-control" />
                    <span asp-validation-for="Slug" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ItemType" class="control-label"></label>
                    <input asp-for="ItemType" class="form-control" />
                    <span asp-validation-for="ItemType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-success">Update</button>
                <a asp-action="Index" class="btn btn-danger">Back to List</a>
            </form>
        </div>
    </div>
</div>

BusinessApp.MvcWebUI/Views/Tags/Index.cshtml
@model IEnumerable<BusinessApp.CarpetWash.Entities.Concrete.Tag>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Responsive table -->
<div class="col-md-12">
    <div class="panel panel-default">
        <header class="panel-heading"><a asp-controller="Tags" asp-action="Create">Create New</a></header>
        <div class="panel-body">
            <table class="table table-striped footable">
                <thead>
                    <tr>
                        <th data-toggle="phone,tablet">Content Id</th>
                        <th data-toggle="true">Tag Name</th>
                        <th data-hide="phone,tablet">Created At</th>
                        <th data-hide="phone,tablet">Updated At</th>
                        <th data-hide="phone">Action</th>
                        <th data-hide="phone">Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Content.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CreatedAt)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UpdatedAt)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                        <td data-value="3"><span class="label label-warning">Suspended</span></td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- /Responsive table -->

<style>
    table table-striped footable, th, td {
        vertical-align: middle !important;
    }
</style>